baseURL = "https://sensorimotor.de/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Sensorimotor"
theme = "hugo-theme-learn"

license = "MIT"
homepage = "https://sensorimotor.de"
repo = "https://github.com/sensorimotor/docs"
min_version = 0.49

[params]
  editURL = "https://github.com/sensorimotor/website/edit/master/content/"
  description = "Sensorimotor Documentation"
  themeVariant = "sensorimotor"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
name = "Sensorimotor"
title = "Sensorimotor"
languageName = "English"


[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-envelope'></i></i> &nbsp;Imprint"
identifier = "cn"
url = "/contact"
weight = 11


[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Source code"
identifier = "ds"
url = "https://github.com/sensorimotor/website/"
weight = 10
